FROM node:20
WORKDIR /app
COPY apps/web /app/apps/web
WORKDIR /app/apps/web
RUN [ -f package.json ] || (npm create vite@latest . -- --template react && npm i)
CMD ["npm","run","dev","--","--host","0.0.0.0"]
