[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shepards-generator"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
sdesk-gen = "generator.cli:main"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["generator*"]
exclude = ["tests*", "inputs*", "jobs*", "outputs*"]
